<?php include "header.phtml" ?>
<!---------- Body starts --------------->
<h1>Login</h1>
<form method="POST">
    <label><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="username" required>
    
    <label><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="password" required>
    
    <button type="submit" name="login">Login</button>
</form>

<br>
<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>