<?php include "header.phtml" ?>
<!---------- Body starts --------------->
<h1>Login</h1>
<form method="POST" action="../../index.php">
    <label><b>Username</b></label>
    <input type="text" name="username" value="<?= $accountId ?>" required>
    
    <label><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="password" required>
    
    <button type="submit" name="login">Login</button>
</form>

<p>Invalid username and/or password.</p>

<br>
<!---------- Body ends -------------------->
<?php include "footer.phtml" ?>