<?php include "header.phtml" ?>
<!-- Base code provided by Andrew Gilman <a.gilman@massey.ac.nz> -->
<h1>Accounts</h1>
<p>The accounts are:</p>
<table>
    <tr class="column_header">
        <th class="id_num">ID</th>
        <th>Username</th>
        <th>Action</th>
    </tr>
    <?php foreach ($accounts as $account) { ?>
    <tr class="data_column">
        <td class="id_num"><?= $account->getId() ?></td>
        <td><?= $account->getName() ?></td>
        <td><a href= <?= $linkTo('accountDelete', ['id' => $account->getId()]);?> >delete</a></td>
    </tr>
    <?php } ?>
</table>
<br>
<a href=<?= $linkTo('accountCreate'); ?>>Create new account.</a>
<br>
<?php include "footer.phtml" ?>