<?php include "header.phtml" ?>
<h1>Login</h1>
<form method="POST">
    <table>
        <tr>
            <td><label>Username</label></td>
            <td><input placeholder="Enter Username" name="username" required></td>
        </tr>
        <tr>
            <td><label>Password</label></td>
            <td><input type="password" placeholder="Enter Password" name="password" required></td>
        </tr>
        <tr>
            <td></td>
            <td><button name="login">Login</button></td>
        </tr>
    </table>
</form>
<br>
<?php include "footer.phtml" ?>
